import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";

import LanguageProvider from "@/components/language/LanguageProvider";
import {
  LANGUAGE_COOKIE_NAME,
  supportedLanguages,
  type LanguageCode,
} from "@/data/translations";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function isLanguageCode(value: string | undefined): value is LanguageCode {
  return supportedLanguages.some((language) => language.code === value);
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const storedLanguage = (await cookies()).get(LANGUAGE_COOKIE_NAME)?.value;
  const initialLanguage = isLanguageCode(storedLanguage)
    ? storedLanguage
    : "en";

  return (
    <html
      lang={initialLanguage}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LanguageProvider initialLanguage={initialLanguage}>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
